//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPS_Service.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LPSDBEntities : DbContext
    {
        public LPSDBEntities()
            : base("name=LPSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LPS_TOKEN> LPS_TOKEN { get; set; }
        public virtual DbSet<LPS_LOG_SIGNIN> LPS_LOG_SIGNIN { get; set; }
        public virtual DbSet<LPS_ACCOUNT_DEPOSIT> LPS_ACCOUNT_DEPOSIT { get; set; }
        public virtual DbSet<LPS_CUSTOMER_GROUP> LPS_CUSTOMER_GROUP { get; set; }
        public virtual DbSet<LPS_CUSTOMER_RATING> LPS_CUSTOMER_RATING { get; set; }
        public virtual DbSet<LPS_CUSTOMER> LPS_CUSTOMER { get; set; }
    }
}
