//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPS_Service.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPS_CUSTOMER_GROUP
    {
        public string CUSTOMER_GROUP_NO { get; set; }
        public string CUSTOMER_GROUP_NAME { get; set; }
        public string CIF_KEY { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_GROUP_RELATION { get; set; }
        public string ASDATE { get; set; }
    }
}
