//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPS_Service.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPS_CUSTOMER_RATING
    {
        public string CIF_KEY { get; set; }
        public string RATING_COMPANY { get; set; }
        public string RATING_TYPE { get; set; }
        public string RATING { get; set; }
        public string RATING_DATE { get; set; }
        public string ASDATE { get; set; }
    }
}
