//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPS_Service.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPS_ACCOUNT_DEPOSIT
    {
        public string CIFNO { get; set; }
        public string ACCTNO { get; set; }
        public string PROCD { get; set; }
        public string ACTYPE { get; set; }
        public string All_Product_ALCO { get; set; }
        public Nullable<decimal> CBAL { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public string ISSDATE { get; set; }
        public string MATDT8 { get; set; }
        public string ASDATE { get; set; }
    }
}
