//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPS_Service.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPS_CUSTOMER
    {
        public string AO_KEY { get; set; }
        public int CIF_KEY { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string REGISTER_DATE { get; set; }
        public string CUSTOMER_ADDRESS { get; set; }
        public string TELEPHONE { get; set; }
        public string FAX { get; set; }
        public Nullable<int> NO_OF_STAFF { get; set; }
        public Nullable<decimal> NET_PROFIT { get; set; }
        public Nullable<decimal> NET_ASSET { get; set; }
        public string BUSINESS_SIZE { get; set; }
        public string BUSINESS_SIZE_DESCRIPTION { get; set; }
        public string CUSTOMER_RATING { get; set; }
        public string WATCHLIST_FLAG { get; set; }
        public string RESCHEDULE_FLAG { get; set; }
        public string TDR_FLAG { get; set; }
        public string ASDATE { get; set; }
    }
}
